version: "2.0"
services:
  bind:
    container_name: bind-wator
    image: bind
    volumes:
      - ./bind/conf:/etc/bind
      - ./bind/cache:/var/cache/bind
    ports:
      - 53:53/udp
      - 53:53/tcp
    restart: always
    
