version: '3'
services:
  bind-dameon:
    image: bind
    volumes:
      - ./bind/conf:/etc/bind
      - ./bind/cache:/var/cache/bind
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 32M
        reservations:
          cpus: '0.5'
          memory: 16M
  nginx-dameon:
    image: nginx
    networks:
      - outside
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/certs:ro
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/conf/tcp.conf.d:/etc/nginx/tcp.conf.d
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 32M
        reservations:
          cpus: '0.2'
          memory: 16M
  certbot-dameon:
    image: certbot/certbot
    networks:
      - outside
    volumes:
      - ./certbot:/wc
      - ./certbot/etc:/etc/letsencrypt
    working_dir: "/wc"
    command: ./create.sh
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 32M
        reservations:
          cpus: '0.2'
          memory: 16M
networks:
  outside:
    external:
      name: "host"
      
    
