version: '3'
services:
  bind-dameon:
    image: bind
    volumes:
      - ./bind/conf:/etc/bind
      - ./bind/cache:/var/cache/bind
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 32M
        reservations:
          cpus: '0.1'
          memory: 16M
  nginx-dameon:
    image: nginx
    networks:
      - outside
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/conf/tcp.conf.d:/etc/nginx/tcp.conf.d
      - ./certbot/etc/:/etc/certs:ro
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 32M
        reservations:
          cpus: '0.1'
          memory: 16M
networks:
  outside:
    external:
      name: "host"
      
    
