version: '3'
services:
  bind-dameon:
    image: bind
    volumes:
      - ./bind/conf:/etc/bind
      - ./bind/db.wator.xyz:/etc/bind/db.wator.xyz
      - ./bind/cache:/var/cache/bind
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 8M
        reservations:
          cpus: '0.1'
          memory: 4M
  nginx-dameon:
    image: nginx:stable
    networks:
      - outside
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/conf/tcp.conf.d:/etc/nginx/tcp.conf.d
      - ./certbot/etc/:/etc/certs:ro
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 8M
        reservations:
          cpus: '0.1'
          memory: 4M
  certbot-renew:
    image: certbot/certbot
    networks:
      - outside
    volumes:
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
      - ./certbot/log:/var/log/letsencrypt
    command: renew
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 8M
        reservations:
          cpus: '0.01'
          memory: 4M
networks:
  outside:
    external:
      name: "host"
      
    
