version: '2'
services:
   nginx:
     build: ./nginx
     image: nginx
     container_name: nginx-wator
     volumes:
       - certs:/etc/letsencrypt
       - certs-data:/data/letsencrypt
     ports:
       - 443:443
