version: '2'
services:
  nginx-proxy:
    image: nginx:stable-alpine
    container_name: nginx-wator
    ports:
      - 443:443
    volumes:
      - ./nginx/certs:/etc/certs:ro
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
    restart: always
