version: '2'
services:
  dnsmasq:
    restart: always
    image: andyshinn/dnsmasq
    container_name: dnsmasq
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    extra_hosts:
      - "www.wator.xyz: 133.130.106.202"
    cap_add:
      - NET_ADMIN
